Ready to Test
alvls/mp2-lab1-set pull request #1
Opened 2021-09-25 16:28 UTC by Sergey-Zagrebin

2021-09-26 13:11 UTC, Sergey-Zagrebin commented
Александр Владимирович, здравствуйте, не получается запустить тесты, ошибка сборки. sln обновлял. Код написан, но тесты не запускаются. Пытался всё переустановить и добавить cpp свои - не сработало.

2021-09-27 10:08 UTC, Sergey-Zagrebin commented
Я переустановил VS скачав все доп пакеты на 8 гб, оно грузилось 10 сек и съело всю память, но тесты запустились, все положительны)

2021-10-06 20:26 UTC, alvls commented
![изображение](https://user-images.githubusercontent.com/5449780/136277832-21f67fee-ee83-4ee0-a458-18cd408bf167.png)
Сергей, вот так у меня выглядят ваши тесты.

2021-10-07 17:44 UTC, sergey31415926 commented
Понял свою ошибку, он не все тесты показывал и из-за критического бага просто выдавал ошибку в gtest и останавливал дальнейшие тесты. Всё поправил, 46 тестов проходит

2021-10-07 18:03 UTC, alvls requested changes

2021-10-07 18:03 UTC, alvls commented on src/tbitfield.cpp
>  }
В этих методах ошибка (одна и та же). Найдите ее и добавьте на нее тест в проект с тестами.

2021-10-07 18:03 UTC, alvls commented on src/tbitfield.cpp
>  }
И в этих методах та же ошибка (см. выше). Найдите ее и добавьте на нее тест в проект с тестами.

2021-10-07 18:07 UTC, alvls requested changes

2021-10-07 18:07 UTC, alvls commented on src/tbitfield.cpp
>  }
В этом методе ошибка. Исправьте.

2021-10-08 10:09 UTC, alvls commented
Пока исправлено не все. И не добавлены тесты.

2021-10-08 20:21 UTC, alvls requested changes

2021-10-08 20:21 UTC, alvls commented on test/test_tbitfield.cpp
> +
Тесты нужно сделать на 10 бит.

2021-10-09 07:51 UTC, alvls commented
| Работа  принята          |      |
| ------------------------ | ---- |
| __Ваш текущий балл:__    |      |
| Функциональность:        | 4,0  |
| Качество проектирования: | 2,0  |
| Качество  кода:          | 1,9  |
| Бонус:                   | 0,0  |
| Штраф:                   | 0,0  |
| __Итого:__               | 7,9  |

2021-10-09 07:52 UTC, closed without merging