Tsvetkov A.
alvls/mp2-lab1-set pull request #12
Opened 2021-10-05 12:04 UTC by a1xsa

2021-10-07 11:47 UTC, alvls requested changes

2021-10-07 11:47 UTC, alvls commented on src/tbitfield.cpp
>  }
В этих методах ошибка (одна и та же). Найдите ее и добавьте на нее тест в проект с тестами.
Аналогичная проблема и в методе GetMemIndex

2021-10-11 05:31 UTC, a1xsa commented
Извините, поздновато увидел ваше сообщение.

2021-10-11 06:50 UTC, alvls commented on src/tset.cpp
> +    return (*this);
При прошлой проверке не заметил - ваша версия отрицания меняет аргумент. Это, конечно, неоднозначно, но, мое мнение, лучше возвращать новый объект.

2021-10-11 06:51 UTC, alvls commented
| Работа  принята          |      |
| ------------------------ | ---- |
| __Ваш текущий балл:__    |      |
| Функциональность:        | 4,0  |
| Качество проектирования: | 2,0  |
| Качество  кода:          | 2,0  |
| Бонус:                   | 0,0  |
| Штраф:                   | 1,0  |
| __Итого:__               | 7,0  |

2021-10-12 12:08 UTC, closed without merging