Task1
alvls/mp2-lab1-set pull request #21
Opened 2023-10-03 16:04 UTC by Gn4ik

2023-10-13 11:12 UTC, alvls requested changes

2023-10-13 11:12 UTC, alvls commented on samples/sample_prime_numbers.cpp
> +#include "gtest/gtest.h"
Это здесь зачем?

2023-10-13 14:20 UTC, Gn4ik commented on samples/sample_prime_numbers.cpp
> +#include "gtest/gtest.h"
При первых запусках разбирался с ошибками и библиотекой, забыл удалить

2023-10-16 16:42 UTC, alvls commented
Вот что выводится на консоль в примере
![изображение](https://github.com/alvls/mp2-lab1-set/assets/5449780/cb0a1854-5655-40de-a6dc-e081505b2692)

А должны выводиться нули и единицы. Исправьте.

2023-10-16 18:10 UTC, alvls commented
Теперь, в целом, все хорошо. Минорное замечание: в разных файлах разное выравнивание кода.

| Работа  принята          |      |
| ------------------------ | ---- |
| __Ваш текущий балл:__    |      |
| Функциональность:        | 4,0  |
| Качество проектирования: | 2,0  |
| Качество  кода:          | 1,9  |
| Бонус:                   | 0,0  |
| Штраф:                   | 0,0  |
| __Итого:__               | 7,9  |

2023-10-16 18:11 UTC, closed without merging