Крайнев А. ЛР1
alvls/mp2-lab1-set pull request #6
Opened 2021-09-27 19:34 UTC by AlexanderOfficial

2021-10-07 08:54 UTC, alvls commented
Александр, замечания:
1. Не нужно коммитить на гитхаб (да и в репозиторий вообще) ничего, кроме исходников. Сейчас у вас 101 файл, а нужных из них всего несколько. Желательно удалить из репозитория все лишнее.
2. Зачем вы модифицировали файл sample_prime_numbers.cpp? Теперь проект-сэмпл не компилируется. Верните все, как было.
3. В этой работе можно добавить новые тесты, если хотите, но нельзя модифицировать уже существующие. Верните их в исходный вид.

2021-10-07 17:19 UTC, AlexanderOfficial commented
1. Почему-то у меня не было файла .gitignore, и возможно поэтому выгрузилось так много лишних файлов на гит.
2. Вернул в sample_prime_numbers.cpp все как было изначально.

2021-10-07 18:13 UTC, alvls requested changes

2021-10-07 18:13 UTC, alvls commented on src/tbitfield.cpp
> +}
В этом методе ошибка. Исправьте.

2021-10-08 06:29 UTC, alvls commented
Александр, теперь все в порядке. Оценку выставлю после того, как наведете порядок в репозитории (удалите все лишнее).

2021-10-08 17:49 UTC, alvls commented
Не видно, чтобы что-то поменялось после последнего коммита.

2021-10-08 18:03 UTC, AlexanderOfficial commented
Все в порядке, я в процессе)
Пытаюсь с git rm --cached -r разобраться для удаления этих файлов, просто пока не очень получается

2021-10-08 18:05 UTC, alvls commented
ОК. Напишите тогда, когда можно будет смотреть.

2021-10-08 18:46 UTC, AlexanderOfficial commented
Можно смотреть.

2021-10-08 18:51 UTC, alvls commented
Ладно, почти получилось...
| Работа  принята          |      |
| ------------------------ | ---- |
| __Ваш текущий балл:__    |      |
| Функциональность:        | 4,0  |
| Качество проектирования: | 2,0  |
| Качество  кода:          | 2,0  |
| Бонус:                   | 0,0  |
| Штраф:                   | 0,0  |
| __Итого:__               | 8,0  |

2021-10-08 18:51 UTC, closed without merging